[package]
name = "rusmarc_raw"
version = "0.1.0"
edition = "2021"

[dependencies]
rusmarc_raw_macros = { path = "../rusmarc_raw_macros/" }
serde = { version = "1.0.215", features = ["serde_derive"] }
serde_json = "1.0.133"
